### ISSUE TITLE
Please explain type inference

### ISSUE THREAD

**Issue by Rudxain** [gleam-lang/language-tour#134]
The sub-string **"infer" occurs 0 times** in the "Everything" view, and "Type annotations" is very vague about how inference works.

I was surprised (in a good way) when [I learned function parameter-types are inferred according to passed arguments on a per-call-site basis](https://github.com/gleam-lang/gleam/discussions/2713#discussioncomment-9034764), rather than inferring once and propagating the type homogeneously to all call-sites. This allows `fn`s to be implicitly generic (no explicit type params!)

**Comment by lpil** [comment]
This is an introduction to Gleam, so it does not detail the type inference algorithm, or any other complexities of the language. The student is encouraged to experiment and learn how it works, which is why an editor and compiler is provided.
