### ISSUE TITLE
Record accessors - field name equality

### ISSUE THREAD

**Issue by rokf** [gleam-lang/language-tour#14]
Hi,

The Record accessors lesson contains the following paragraph.

> The accessor syntax can only be used for fields that are in the same position and have the same type for all variants of the custom type.

Should we perhaps also mention that the name of the fields has to match as well across all of the variants for this to work? It's not just the position and type that have to match.

This one is a bit weird and I wasn't sure of I should even open an issue for it, therefore feel free to close it if you think that I'm overthinking 😅 

Thanks 😄

**Comment by lpil** [comment]
If there's confusion it can be improved! I'll do that now. Thanks
