### ISSUE TITLE
Variable patterns - code example doesn't match the description

### ISSUE THREAD

**Issue by rokf** [gleam-lang/language-tour#15]
Hi,

I've noticed one thing in the `Variable patterns` lesson, the description mentions variables and how they can be used in bodies of matching clauses, the example doesn't contain such a clause though.

I suppose that the example could be updated to match the description or vice versa.

https://tour.gleam.run/flow-control/variable-patterns/

Thanks!

**Comment by lpil** [comment]
Thank you
