### ISSUE TITLE
Ints and Floats - inequality example

### ISSUE THREAD

**Issue by rokf** [gleam-lang/language-tour#16]
Hi,

I've noticed that https://tour.gleam.run/basics/ints/ and https://tour.gleam.run/basics/floats/ don't contain examples of inequality check operators (`!=`).

I suggest that we add this since these two lessons are the first to introduce the operator syntax.

Languages sometimes use different syntax for these, i.e. `~=` in Lua, which is another reason why this would be helpful.

Thanks! 😃

**Comment by lpil** [comment]
Oh yes, there's nothing on equality at all. I'll add that now.
