### ISSUE TITLE
No example of record destructuring in a let assignment

### ISSUE THREAD

**Issue by lpil** [gleam-lang/language-tour#56]

**Comment by xxKeefer** [comment]
Hey there 👋🏻, would love to hep out with this one!

Just some clarifying questions, should there be an extra step in the tour like in between Records and Record Accessors under Data Types or should the example for Records be updated?

Looking at the current Record page and it's example, to be able to destructure a `SchoolPerson`  i think it would require the use of a case or let assert to destructure. I feel as if using those concepts would make the example of record destructuring less clear, especially in the case of let assert. 

If i can get a point intthe right directions here i'll get started ASAP. <3

**Comment by lpil** [comment]
A new lesson on record patterns or something like that sounds good to me!
