### ISSUE TITLE
Missing details for bit array options

### ISSUE THREAD

**Issue by brettcannon** [gleam-lang/language-tour#58]
This is a more generic response to #57 .

https://tour.gleam.run/data-types/bit-arrays/ lists various options, but they don't specify things like which ones require an argument (like `size`), ones that require more than just themselves (e.g. `unit`), how to change `int` to not be "a default size of 8 bits", etc.

The list is also missing:
- utf8_codepoint
- utf16_codepoint
- utf32_codepoint
- signed
- unsigned
based on the [error message](https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/parse/error.rs#L82-L99).

**Comment by lpil** [comment]
Thank you
