### ISSUE TITLE
Commenting Code

### ISSUE THREAD

**Issue by nickbar01234** [gleam-lang/language-tour#62]
## Proposal

When walking through the language tutorial, it would be nice to have a quick method to comment / uncomment code block for testing purposes.

From a quick scan through the code, I don't think this is currently implemented in the online editor yet. Would it be possible / make sense to insert `//` when user presses `cmd + /` for Mac and `ctrl + /` for Windows?

**Comment by lpil** [comment]
Hello! This would be an issue for Codeflask, the editor we use.
