### ISSUE TITLE
Bug: un-clickable "table of contents" footer at the bottom of the everything page

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/language-tour#69]
The table of contents footer appears on mobile as a large block at the bottom of the page. This button is seemingly unclickable. 

Phone: iPhone 12

![image](https://github.com/gleam-lang/language-tour/assets/22840519/6b3f8b11-8518-460d-b0db-34d0d95e14a9)

**Comment by lpil** [comment]
Thank you
