### ISSUE TITLE
Feature: Ability to see generated code

### ISSUE THREAD

**Issue by wezm** [gleam-lang/language-tour#8]
It would be good for understanding how Gleam compiles code to be able to see then generated JS in the tour. In a similar way to how the [ReScript](https://rescript-lang.org/try) and [Melange](https://melange.re/v2.2.0/playground/) playgrounds let you edit the code and then see the compiled result live.

**Comment by lpil** [comment]
Hello! It would be good to have this feature, but this is not the place for it as this is an introduction to the language.

I'm not planning to make this myself as I have more pressing work, but it would be easy for someone else to do this.

**Comment by lpil** [comment]
It's not appropriate for the tour, it will not be added.
