### ISSUE TITLE
Relative paths for css

### ISSUE THREAD

**Issue by ellipticview** [gleam-lang/language-tour#94]
I cloned and built this repo, and was expecting to view the tour by opening public/index.html from the filesystem. However this does not work because all references are absolute instead of relative. E.g.
<link rel="stylesheet" href="/css/pages/lesson.css"> instead of <link rel="stylesheet" href="css/pages/lesson.css">

Is this by design, or can they be changed to relative references?

**Comment by lpil** [comment]
Even if we loaded the CSS the rest of the tour wouldn't work. We need to be served from a web server for the wasm compiler and code runner to work unfortunately.
