### ISSUE TITLE
CSS bug: border overlaps content when the output box has a scrollbar

### ISSUE THREAD

**Issue by lpil** [gleam-lang/language-tour#96]
Scroll down to see

<img width="860" alt="image" src="https://github.com/gleam-lang/language-tour/assets/6134406/3491c788-72b1-40c6-a39a-e4840a78b9d4">

**Comment by silver-shadow** [comment]
I'm new to contributing to open source projects, but I wanted to take a shot at fixing this CSS bug. I've opened a pull request ([#97](https://github.com/gleam-lang/language-tour/pull/97)) to address the issue.

Any suggestions appreciated.

**Comment by lpil** [comment]
Thank you @silver-shadow !!
