### ISSUE TITLE
Code editor not visible on some pages for small viewports

### ISSUE THREAD

**Issue by thorhj** [gleam-lang/language-tour#99]
The code editor is completely blocked by the output pane on some pages, completely hiding the most important part of the lesson. This happens on pages with a long text and multiple output lines, like `/basics/floats/`.

![language-tour-bug](https://github.com/gleam-lang/language-tour/assets/4330107/40f4d9c9-371e-4da4-9b1b-5c6b5f5608fb)

**Comment by thorhj** [comment]
I have attempted to fix this in #100, but be aware that my CSS skills are severely lacking 😆

**Comment by lpil** [comment]
Thanks again, and thank you for the screen recordings. Super helpful
